### ISSUE TITLE
file_get_contents not work on nodejs

### ISSUE THREAD

**Issue by ChandraNakka** [kvz/phpjs#179]
**My test JS file code is:**

```js
var php = require('phpjs');
var dat = php.file_get_contents("http://www.google.com/robots.txt");
php.echo(dat);
```

**Output is :**

```text
nakka@nakka-desktop:~/NodeJS$ node test.js

/home/nakka/NodeJS/node_modules/phpjs/build/npm.js:3086
window.ActiveXObject ? new ActiveXObject('Microsoft.XMLHTTP') : new XMLHttpReq
                                                                    ^
ReferenceError: XMLHttpRequest is not defined
    at Object.exports.file_get_contents (/home/nakka/NodeJS/node_modules/phpjs/build/npm.js:3086:90)
    at Object.<anonymous> (/home/nakka/NodeJS/test.js:3:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```
Please solve this error...

**Comment by theaqua** [comment]
Try [superagent](http://visionmedia.github.io/superagent/).
